=pod

=encoding utf-8

=head1 NAME

AnyEvent::Sleep - Sleep for n seconds while events still fire

=head1 VERSION

version 0.1.0

=head1 SYNOPSIS

    use AnyEvent::Sleep;

    # Sleep for 3 seconds without blocking events from firing
    sleep 3;

    # Sleep for an hour
    sleep_until time() + 3600;

=head1 DESCRIPTION

This module provides event-loop safe sleep loops.  Sleeps can be useful to
setup timeouts-- try something, sleep, if it hasn't returned cancel it.

If you are using Coro, then sleep is probably better gotten from
L<Coro::AnyEvent>.

The helpers in this module are exported by L<Sub::Exporter>.

=head1 HELPERS

=head2 sub sleep( Num $secs ) is export

Sleep for $secs while allowing AnyEvent events to emit (and Coroutine threads to run)

=head2 sub sleep_until( Num $epochtime ) is export

Sleep until $epochtime while allowing events to emit (and Coroutine threads to run)

=head1 SEE ALSO



=over 4

=item *

L<Coro::AnyEvent|Coro::AnyEvent>

=back

=head1 SOURCE

The development version is on github at L<http://https://github.com/iarna/AnyEvent-Sleep>
and may be cloned from L<git://https://github.com/iarna/AnyEvent-Sleep.git>

=for :stopwords cpan testmatrix url annocpan anno bugtracker rt cpants kwalitee diff irc mailto metadata placeholders metacpan

=head1 SUPPORT

=head2 Websites

The following websites have more information about this module, and may be of help to you. As always,
in addition to those websites please use your favorite search engine to discover more resources.

=over 4

=item *

MetaCPAN

A modern, open-source CPAN search engine, useful to view POD in HTML format.

L<http://metacpan.org/release/AnyEvent-Sleep>

=back

=head2 Bugs / Feature Requests

Please report any bugs at L<https://github.com/iarna/AnyEvent-Sleep/issues>.

=head2 Source Code

The code is open to the world, and available for you to hack on. Please feel free to browse it and play
with it, or whatever. If you want to contribute patches, please send me a diff or prod me to pull
from your repository :)

L<https://github.com/iarna/AnyEvent-Sleep>

  git clone https://github.com/iarna/AnyEvent-Sleep.git

=head1 AUTHOR

Rebecca Turner <becca@referencethis.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Rebecca Turner.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=head1 DISCLAIMER OF WARRANTY

BECAUSE THIS SOFTWARE IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE SOFTWARE, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT
WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER
PARTIES PROVIDE THE SOFTWARE "AS IS" WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE
SOFTWARE IS WITH YOU. SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME
THE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR
REDISTRIBUTE THE SOFTWARE AS PERMITTED BY THE ABOVE LICENCE, BE LIABLE
TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL, OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A
FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF
SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
DAMAGES.


=cut

